train:
  _target_: src.datasets.GeoPlantDataset
  split: "train"
  local_path: "./data"
  instance_transforms: ${transforms.instance_transforms.train}
  limit: 90000
val:
  _target_: src.datasets.GeoPlantDataset
  split: "train"
  local_path: "./data"
  instance_transforms: ${transforms.instance_transforms.inference}
  limit: 1000
