train:
  _target_: src.datasets.GeoPlantDataset
  split: "train"
  local_path: null
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.GeoPlantDataset
  split: "val"
  local_path: null
  instance_transforms: ${transforms.instance_transforms.train}