train:
  _target_: src.datasets.geoplant_dataset_clusterized.GeoPlantDataset
  split: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.geoplant_dataset_clusterized.GeoPlantDataset
  split: "val"
  instance_transforms: ${transforms.instance_transforms.train}