train:
  _target_: src.datasets.GeoPlantDataset
  split: "train"
  local_path: data
  use_for_training_adaptive_k: True
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.GeoPlantDataset
  split: "val"
  local_path: data
  use_for_training_adaptive_k: True
  instance_transforms: ${transforms.instance_transforms.train}