defaults:
  - model: tabular_transformer
  - writer: wandb
  - metrics: stable
  - datasets: geoplant_clusterized
  - dataloader: stable
  - transforms: stable
  - _self_

num_classes: 11255
model_transforms: []

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-4
  betas: [0.9, 0.95]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 2e-4
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}

loss_function:
  _target_: src.loss.AsymmetricLossWrapper
  gamma_neg: 4
  gamma_pos: 1
  clip: 0.05

trainer:
  log_step: 200
  n_epochs: 30
  epoch_len: 2000
  max_grad_norm: 2.0
  accum_steps: 1
  device_tensors: ["climate_features", "elevation_features", "human_footprint_features", "land_cover_features", "soil_grids_features", "target"]
  resume_from: null
  device: auto
  override: True
  monitor: "max val_Jaccard"
  save_period: 100000000
  early_stop: ${trainer.n_epochs}
  save_dir: "saved/tabular_transformer"
  seed: 1
