defaults:
  - model: time_fusion
  - writer: wandb
  - metrics: stable
  - datasets: geoplant
  - dataloader: stable
  - transforms: stable
  - _self_

num_classes: 11255
model_transforms: []

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-4
  betas: [0.9, 0.95]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 2e-4
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}

loss_function:
  _target_: src.loss.AsymmetricLossWrapper
  gamma_neg: 4
  gamma_pos: 1
  clip: 0.05

trainer:
  log_step: 50
  n_epochs: 1
  epoch_len: 500
  max_grad_norm: 1.0
  accum_steps: 1
  device_tensors: ["bioclimatic", "landsat", "target"]
  resume_from: null
  device: auto
  override: True
  monitor: "max val_Jaccard"
  save_period: -1
  early_stop: ${trainer.n_epochs}
  save_dir: "saved/time_fusion"
  seed: 1
