defaults:
  - model: baseline
  - writer: wandb
  - metrics: stable
  - datasets: geoplant
  - dataloader: stable
  - transforms: stable
  - _self_

num_classes: 11254
model_transforms: []

optimizer:
  _target_: torch.optim.AdamW
  lr: 6e-4
  weight_decay: 1e-1
  betas: [0.9, 0.95]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 6e-4
  pct_start: 0.02
  div_factor: 10.0
  final_div_factor: 10.0
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos

loss_function:
  _target_: src.loss.BCELossWrapper

trainer:
  log_step: 50
  n_epochs: 60
  epoch_len: 500
  max_grad_norm: 1.0
  accum_steps: 1
  device_tensors: ["satellite", "bioclimatic", "landsat", "table_data", "target"]
  resume_from: null
  device: auto
  override: True
  monitor: "max val_F1"
  save_period: -1
  early_stop: ${trainer.n_epochs}
  save_dir: "saved/mmm"
  seed: 1
