defaults:
  - model: resnet_dual_path
  - writer: wandb
  - metrics: stable
  - datasets: geoplant
  - dataloader: stable
  - transforms: stable
  - _self_

num_classes: 11254
model_transforms: []

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-4
  betas: [0.9, 0.95]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-4
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}

loss_function:
  _target_: src.loss.AsymmetricLossWrapper
  gamma_neg: 4
  gamma_pos: 1
  clip: 0.05

trainer:
  log_step: 50
  n_epochs: 60
  epoch_len: 500
  max_grad_norm: 1.0
  accum_steps: 1
  device_tensors: ["satellite", "bioclimatic", "landsat", "table_data", "climate_features", "elevation_features", "human_footprint_features", "land_cover_features", "soil_grids_features", "target"]
  resume_from: null
  device: auto
  override: True
  monitor: "max val_F1"
  save_period: -1
  early_stop: ${trainer.n_epochs}
  save_dir: "saved/mmm"
  seed: 1
